// This file is generated by Prismic local builder. Update with care!

export { default as CallToAction } from './CallToAction'
export { default as CustomerLogos } from './CustomerLogos'
export { default as PricingTable } from './PricingTable'
